{% set name = "conda-replicate" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cswartzvi/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 75b2aa1b958c2865e6b09e946cd518d1a7be0bb4b86b8da95ccf2818bb5fa8ef

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - conda-replicate = conda_replicate.cli:app

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - conda >=4.12
    - conda-build >=3.19
    - networkx
    - rich
    - click >=8.0
    - rich-click
    - fsspec
    - aiohttp
    - pydantic
    - requests
    - pyyaml

test:
  imports:
    - conda_replicate

  commands:
    - conda-replicate --help

about:
  home: https://github.com/cswartzvi/conda-replicate
  license: MIT
  license_file: LICENSE
  summary: 'Manage local mirrored anaconda channels.'

extra:
  recipe-maintainers:
    - cswartzvi
